language: rust
sudo: required
addons:
  apt:
    packages:
      - libssl-dev
      - pkg-config
      - cmake
      - zlib1g-dev
      - jq
cache: cargo
rust:
  - stable
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

branches:
  only:
    - /^arielmakestuff\/.+$/
    - develop
    - master

install: |
  rustup component add rustfmt
  rustup component add clippy
before_cache: |
  JUST_VER="0.4.4"
  TARPAULIN_VER="0.8.3"

  CUR_JUST_VER=$(just -V 2> /dev/null)
  EXPECTED_JUST_VER="just v$JUST_VER"
  if [ "$CUR_JUST_VER" != "$EXPECTED_JUST_VER" ]; then
    cargo install -f --version $JUST_VER -- just
  fi

  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    CUR_TARPAULIN_VER=$(cargo tarpaulin -V 2> /dev/null)
    EXPECTED_TARPAULIN_VER="cargo-tarpaulin version: $TARPAULIN_VER"
    if [ "$CUR_TARPAULIN_VER" != "$EXPECTED_TARPAULIN_VER" ]; then
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install -f --version $TARPAULIN_VER -- cargo-tarpaulin
    fi
  fi

jobs:
  include:
    - stage: manual-iter
      rust: stable
      script:
        - cargo clean
        - cargo build --all
        - cargo fmt --all -- --check
        - cargo clippy --all
    - rust: nightly
      script:
        - cargo clean
        - cargo build --all
        - cargo fmt --all -- --check
        - cargo clippy --all
        - just cov Xml
        - bash <(curl -s https://codecov.io/bash)
    - stage: parser-iter
      rust: stable
      script:
        - cargo clean
        - cargo build --all --no-default-features --features parser-iter
        - cargo fmt --all -- --check
        - cargo clippy --all
        - just test parser-iter
    - rust: nightly
      script:
        - cargo clean
        - cargo build --all --no-default-features --features parser-iter
        - cargo fmt --all -- --check
        - cargo clippy --all
        - just cov-parser-iter Xml
        - bash <(curl -s https://codecov.io/bash)

