language: rust
sudo: required
addons:
  apt:
    packages:
      - libssl-dev
      - pkg-config
      - cmake
      - zlib1g-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

branches:
  only:
    - /^arielmakestuff\/.+$/
    - develop
    - master

install: |
  rustup component add rustfmt
  rustup component add clippy

script:
  - cargo clean
  - cargo build --all
  - cargo fmt --all -- --check
  - cargo clippy --all
  - cargo test --all

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin -v --out Xml --exclude-files src/unix/windows_iter.rs src/windows/path.rs src/windows/windows_iter.rs tests/*
    bash <(curl -s https://codecov.io/bash)
  fi
