strategy:
  matrix:
    windows-stable:
      imageName: 'vs2017-win2016'
      rustup_toolchain: stable
    mac-stable:
      imageName: 'macos-10.13'
      rustup_toolchain: stable
    linux-stable:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: stable

pool:
  vmImage: $(imageName)

steps:
  - template: 'ci/azure/install-rust.yml'
  - script: rustup component add rustfmt
    displayName: Install Rustfmt
  - script: cargo fmt --all -- --check
    displayName: Run Rustfmt
  - script: rustup component add clippy
    displayName: Install Clippy
  - script: cargo clippy --all
    displayName: Run clippy
  - script: cargo build --all --all-features
    displayName: Cargo build
  - script: cargo test --all --all-features
    displayName: Cargo test all features
  - script: cargo test --all --no-default-features --features manual-iter
    displayName: Cargo test manual-iter feature
  - script: cargo test --all --no-default-features --features parser-iter
    displayName: Cargo test parser-iter feature
  - script: cargo bench --bench compare_stdpath
    displayName: Bench stdpath vs pathlib
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
