[package]
name = "pathlib"
version = "0.1.0"
authors = ["Ariel De Ocampo <arielmakestuff@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
derive_more = "0.14"

[dev-dependencies]
proptest = "0.9.1"
